### PR TITLE
bug: wrap html and text bodies in an 'alternative' multipart

### LINKED ISSUE #44: Sending multi-part email sends HTML part as an attachment
### Expected Behavior

Expected behavior is to view e-mail as HTML, with buttons, links etc. But I also want to send text part as fallback, when html can't be displayed

### Actual Behaviour

When I send e-mail with html and text in MultiPartBody the HTML part is sent as an attachment. 
I'm using the code from guiide [https://micronaut-projects.github.io/micronaut-email/latest/guide/#template](url)
The same code sent HTML template as an attachement and in the e-mail is displayed the text part.

I'm using JavaMail API and template engine handlebars.
The content-type header is mixed/multipart

### Steps To Reproduce

Setup EmailConfigProvider eg. for gmail
```
@Singleton
class EmailConfigProvider: MailPropertiesProvider {
    override fun mailProperties(): Properties {
        val emailProperties = Properties()
        emailProperties.put("mail.smtp.host", "smtp.gmail.com")
        emailProperties.put("mail.smtp.port", "587");
        emailProperties.put("mail.smtp.ssl.trust", "smtp.gmail.com");
        emailProperties.put("mail.smtp.ssl.protocols", "TLSv1.2");
        emailProperties.put("mail.transport.protocol", "smtp");
        emailProperties.put("mail.smtp.auth", "true");
        emailProperties.put("mail.smtp.starttls.enable", "true");
        emailProperties.put("mail.debug", "true");
        return emailProperties
    }
}
```

Setup EmailSessionProvider and replace user and password with your credentials 
```
@Singleton
class EmailSessionProvider(
    properties: EmailConfigProvider,
    @Property(name = "online-onboarding.smtp.user") user: String,
    @Property(name = "online-onboarding.smtp.password") password: String
) : SessionProvider {
    private val properties: Properties
    private val user: String
    private val password: String

    init {
        this.properties = properties.mailProperties()
        this.user = user
        this.password = password
    }

    @NonNull
    override fun session(): Session? {
        return Session.getInstance(properties, object : Authenticator() {
            override fun getPasswordAuthentication(): PasswordAuthentication {
                return PasswordAuthentication(user, password)
            }
        })
    }
}
```
Setup function for sending e-mails
```
@Singleton
class EmailService(private val emailSender: EmailSender<*, *>) {

    fun sendMail(email: EmailData): EmailException? {

        try {
            emailSender.send(
                Email.builder()
                    .from(email.from)
                    .to(email.to)
                    .subject(email.subject)
                    .body(
                        MultipartBody(
                            TemplateBody(BodyType.HTML, ModelAndView("email/purchase-created-html", email.variables)),
                            TemplateBody(BodyType.TEXT, ModelAndView("email/purchase-created-text", email.variables))
                        ) //TODO - when I add .html it sends html, but not text
                    )
            )
            return null
        } catch (exception: EmailException) {
            return exception
        }

    }
}
```
You need to create .html and .txt files under resources/views 
Call this function and check for e-mail

### Environment Information

micronautVersion=3.3.3
kotlinVersion=1.6.10

### Example Application

_No response_

### Version

3.3.3

### PR DESCRIPTION
**Pull request by timyates**
Used dockerized mailhog as a local test harness

Checked for binary compatibility, all ok so can be in a patch release

Fixes #44

### CODE REVIEW

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+        @Get("/api/v2/messages")
+        MessageResponse messages()
+    }
+
+    @Introspected
+    @JsonIgnoreProperties(ignoreUnknown = true)
+    @ToString
+    static class MessageResponse {
+
+        int total
```
Comment (sdelamo) [inline email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy:120]: unused

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+        int count
```
Comment (sdelamo) [inline email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy:121]: unused

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+        int start
```
Comment (sdelamo) [inline email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy:122]: unused

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy [hunk 4]
```diff
@@ -0,0 +1,148 @@
...
+        List<Item> items
+    }
+
+    @Introspected
+    @ToString
+    @JsonIgnoreProperties(ignoreUnknown = true)
```
Comment (sdelamo) [inline email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy:128]: unncessary

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy [hunk 5]
```diff
@@ -0,0 +1,148 @@
...
+    static class Item {
+        @JsonProperty("Content")
+        Content content
+    }
+
+    @Introspected
+    @ToString
+    @JsonIgnoreProperties(ignoreUnknown = true)
```
Comment (sdelamo) [inline email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy:136]: unncessary

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy [hunk 6]
```diff
@@ -0,0 +1,148 @@
...
+
+    @Client('${mailhog.uri}')
+    static interface MailhogClient {
+
+        @Get("/api/v2/messages")
+        MessageResponse messages()
+    }
+
+    @Introspected
+    @JsonIgnoreProperties(ignoreUnknown = true)
```
Comment (sdelamo) [inline email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy:116]: unncessary

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy [hunk 7]
```diff
@@ -0,0 +1,148 @@
...
+    private Attachment createSpreadsheetAttachment(String filename, String mediaType) {
+        Attachment.builder()
+                .filename(filename)
+                .contentType(mediaType)
+                .content(SpreadsheetUtils.spreadsheet())
+                .build()
+    }
+
+    @Client('${mailhog.uri}')
+    static interface MailhogClient {
```
Comment (sdelamo) [inline email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy:109]: annotate with `@Requires` `spec.name` to avoid bean pollution`

**Review by sdelamo — APPROVED** [review]
I have refactored the body part to make it easier to understand. At least for my brain.

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy (hunk 4 above)
Comment (sdelamo) [reply email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy]: resolved via https://github.com/micronaut-projects/micronaut-email/pull/45/commits/b0233269069101d88929b0f812d278272a66402c

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy (hunk 6 above)
Comment (sdelamo) [reply email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy]: resolved via https://github.com/micronaut-projects/micronaut-email/pull/45/commits/b0233269069101d88929b0f812d278272a66402c

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy (hunk 5 above)
Comment (sdelamo) [reply email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy]: resolved via https://github.com/micronaut-projects/micronaut-email/pull/45/commits/b0233269069101d88929b0f812d278272a66402c

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy (hunk 7 above)
Comment (sdelamo) [reply email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy:112]: resolved via https://github.com/micronaut-projects/micronaut-email/pull/45/commits/93c20359077de4309dd3983827b8abb64a20c8ea

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy (hunk 1 above)
Comment (sdelamo) [reply email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy]: resolved via https://github.com/micronaut-projects/micronaut-email/pull/45/commits/5bf48a4fd1045e1ba14b7ddde732504abaa564e5

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy (hunk 3 above)
Comment (sdelamo) [reply email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy]: resolved via https://github.com/micronaut-projects/micronaut-email/pull/45/commits/5bf48a4fd1045e1ba14b7ddde732504abaa564e5

File: email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy (hunk 2 above)
Comment (sdelamo) [reply email-javamail/src/test/groovy/io/micronaut/email/javamail/JavaMailBodyAndAttachmentSpec.groovy]: resolved via https://github.com/micronaut-projects/micronaut-email/pull/45/commits/5bf48a4fd1045e1ba14b7ddde732504abaa564e5

File: email-javamail-composer/src/main/java/io/micronaut/email/javamail/composer/DefaultMessageComposer.java [hunk 8]
```diff
@@ -54,9 +56,18 @@
...
+    private static final Logger LOG = LoggerFactory.getLogger(DefaultMessageComposer.class);
+    private static final String SUBTYPE_ALTERNATIVE = "alternative";
+    private static final Map<BodyType, String> BODY_TYPES;
+
+    static {
+        Map<BodyType, String> m = new HashMap<>(2);
+        m.put(BodyType.TEXT, TYPE_TEXT_PLAIN_CHARSET_UTF_8);
+        m.put(BodyType.HTML, TYPE_TEXT_HTML_CHARSET_UTF_8);
+        BODY_TYPES = Collections.unmodifiableMap(m);
+    }
```
Comment (timyates) [inline email-javamail-composer/src/main/java/io/micronaut/email/javamail/composer/DefaultMessageComposer.java:70]: I can't wait for the next java baseline 😉

Comment (sdelamo) [reply email-javamail-composer/src/main/java/io/micronaut/email/javamail/composer/DefaultMessageComposer.java]: Maybe, I got to high on my own supply.
